Archive now default compresses and only deletes if specified

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 copy_flag=0
-compress_flag=0
+compress_flag=1
 ARCHIVE_DIR="$HOME/.archive"
 archive_name=""
 delete_files=0
@@ -14,7 +14,6 @@ function print_usage {
     echo ""
     echo "Options:"
     echo "   -c,--copy                  Copy files into archive directory"
-    echo "   -z                         Compress the file into a tar.gz file before archiving"
     echo "   --name <archive_name>      Name of the archive, if not specified then name of first file is used"
     echo "   --delete                   Delete source files after transferring to archive, cannot be used in conjuction with '-c'"
     echo "   -q,--quiet                 Don't display any output"
@@ -66,10 +65,6 @@ do
 	    copy_flag=1
         shift
 	    ;;
-    -z)
-        compress_flag=1
-        shift
-        ;;
     --name)
         shift
         archive_name="$1"
@@ -101,7 +96,7 @@ else
     then
         printf "Are you sure you want to remove files after transfer? This cannot be undone [y/N]: "
         read resp
-        if [ ${resp^} = "Y" ] 
+        if [ ${resp^} = "Y" ]
         then
             delete_files=1
         else
@@ -115,7 +110,7 @@ else
         archive_name="${1/\//-}"
         archive_name="${archive_name%%.*}"
     fi
-    #echo "$archive_name"   
+    #echo "$archive_name"
     max_width=$(max_arg_width $@)
     max_file_width=$(max_file_name_width $@)
     while [ $# -gt 0 ]
@@ -152,16 +147,16 @@ else
                 rm -r $file_list
             fi
             exit 0
-        elif [ $copy_flag -eq 1 ]
-        then
-            echo "rsync -av $1 $ARCHIVE_DIR/" > $out
-            rsync -av $1 $ARCHIVE_DIR/ > /dev/null
-            test $? -ne 0 && echo "Err: rsync failed" && exit $?
-        else
-            echo "mv $1 $ARCHIVE_DIR/" > $out
-            mv $1 $ARCHIVE_DIR/ 
-            test $? -ne 0 && echo "Err: mv failed" && exit $?
-        fi 
+        # elif [ $copy_flag -eq 1 ]
+        # then
+        #     echo "rsync -av $1 $ARCHIVE_DIR/" > $out
+        #     rsync -av $1 $ARCHIVE_DIR/ > /dev/null
+        #     test $? -ne 0 && echo "Err: rsync failed" && exit $?
+        # else
+        #     echo "mv $1 $ARCHIVE_DIR/" > $out
+        #     mv $1 $ARCHIVE_DIR/
+        #     test $? -ne 0 && echo "Err: mv failed" && exit $?
+        fi
         printf "+%-*s  %-*s  %s\n" $((max_file_width + 4)) "'$file_name'" $((max_width + 4)) "$1" "$(date +'%b %d %Y %H:%M')" >> $ARCHIVE_DIR/.logs/file_history.log
         shift
     done
